"""
Verify each CLI distribution carries the surviving skill set in the right shape.

- Codex ships native plugins (two plugins under dist/codex/plugins/, registered by
  the repo-root .agents/plugins/marketplace.json). No installer, no agents, no
  namespacing suffixes.
- OpenCode ships a plugin (dist/opencode/plugin/) that registers the source skill
  directories (claude-plugins/*/skills) via skills.paths and slash-command wrappers
  via cfg.command. No installer, no command files, no copied payload.
- Pi's package manifest (repo-root package.json) points at the same source skill
  directories and ships prompt-template aliases for the main entrypoints; no
  TypeScript runtime extension, no copied payload.
- Codex's plugin directories are byte-identical copies of the source skill
  directories, regenerated by scripts/sync_dist.py and checked for drift here.

Skill text is host-neutral (tests/test_skill_frontmatter.py enforces it), so every
surface reads the same words: no per-host rewrite exists.

Reviewers are dimensions of the review-code skill, not standalone agents.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DIST = ROOT / "dist"
SYNC_TOOLS = ROOT / ".claude" / "skills" / "sync-tools"


def source_skills(plugin: str) -> tuple[str, ...]:
    skills_dir = ROOT / "claude-plugins" / plugin / "skills"
    return tuple(
        sorted(
            path.name
            for path in skills_dir.iterdir()
            if path.is_dir() and (path / "SKILL.md").is_file()
        )
    )


CORE_SKILLS = source_skills("manifest-dev")
TOOLS_SKILLS = source_skills("manifest-dev-tools")
ALL_SKILLS = CORE_SKILLS + TOOLS_SKILLS
PI_PROMPTS = ("do", "auto", "babysit-pr")

CODE_REVIEW_DIMENSIONS = {
    "change-intent",
    "code-bugs",
    "code-design",
    "code-maintainability",
    "code-simplicity",
    "code-testability",
    "context-file-adherence",
    "defect-class",
    "contracts",
    "docs",
    "operational-readiness",
    "prose-value",
    "test-quality",
    "type-safety",
}
RETIRED_REVIEWER_AGENTS = {f"{d}-reviewer" for d in CODE_REVIEW_DIMENSIONS}
REMOVED_SKILLS = ("verify",)

# The superseded manifest schema gave a gate a `verify:` block (carrying
# `instructions`/`prompt`/`model`) and an optional integer `phase`. Both are
# retired: a gate is now a title, a body, an optional why, and a required
# `kind`. Nothing distributed may reintroduce either field.
RETIRED_GATE_FIELDS = re.compile(r"^[ \t]*(?:verify|phase):", re.MULTILINE)

# A gate example in shipped docs: an `AC-`/`INV-G` heading whose block closes on
# a kind declaration (or the schema template's placeholder for one).
GATE_EXAMPLE_HEADING = re.compile(r"^#{3,4} (?:AC-|INV-G)")
GATE_KIND_LINE = re.compile(
    r"^(?:Judgment|Deterministic|\[Judgment \| Deterministic\]) gate\.$"
)

SELF_INDEPENDENCE_CLAIMS = (
    re.compile(
        r"\bindependent(?:ly)?(?:\s+verified)?\s+"
        r"self(?:[- ]verification|\s+mode)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bself(?:[- ]verification|\s+mode)\b"
        r"[^.;\n]{0,100}\b"
        r"(?:is|uses|employs|launches|invokes|has|gets|receives|requires|"
        r"relies\s+on|(?:is\s+)?(?:performed|evaluated|verified)\s+by)\b"
        r"[^.;\n]{0,80}\b(?:an?\s+)?independent(?:ly)?\b",
        re.IGNORECASE,
    ),
)


def claims_self_verification_is_independent(text: str) -> bool:
    normalized = text.replace("`", "")
    for claim in SELF_INDEPENDENCE_CLAIMS:
        for match in claim.finditer(normalized):
            if not re.search(
                r"\b(?:no|not|never|without)\b|non-independent",
                match.group(0),
                re.IGNORECASE,
            ):
                return True
    return False


# --------------------------------------------------------------------------
# Codex: plugin-native distribution
# --------------------------------------------------------------------------


def codex_plugin_skills(plugin: str) -> set[str]:
    skills_dir = DIST / "codex" / "plugins" / plugin / "skills"
    return {p.name for p in skills_dir.iterdir() if p.is_dir()}


def test_codex_plugins_carry_their_skill_split() -> None:
    assert codex_plugin_skills("manifest-dev") == set(CORE_SKILLS)
    assert codex_plugin_skills("manifest-dev-tools") == set(TOOLS_SKILLS)
    for plugin in ("manifest-dev", "manifest-dev-tools"):
        for skill in codex_plugin_skills(plugin):
            assert (
                DIST / "codex" / "plugins" / plugin / "skills" / skill / "SKILL.md"
            ).is_file()


def test_codex_plugin_versions_match_sources() -> None:
    for plugin in ("manifest-dev", "manifest-dev-tools"):
        source = json.loads(
            (
                ROOT / "claude-plugins" / plugin / ".claude-plugin" / "plugin.json"
            ).read_text(encoding="utf-8")
        )
        codex = json.loads(
            (
                DIST / "codex" / "plugins" / plugin / ".codex-plugin" / "plugin.json"
            ).read_text(encoding="utf-8")
        )
        assert codex["version"] == source["version"], plugin


def test_codex_code_review_skill_carries_every_dimension() -> None:
    refs = (
        DIST
        / "codex"
        / "plugins"
        / "manifest-dev"
        / "skills"
        / "review-code"
        / "references"
    )
    assert {p.stem for p in refs.glob("*.md")} == CODE_REVIEW_DIMENSIONS


def test_codex_does_not_ship_reviewer_agents_or_removed_skills() -> None:
    # No agents directory at all in the plugin-native distribution.
    assert not (DIST / "codex" / "agents").exists()
    for plugin in ("manifest-dev", "manifest-dev-tools"):
        skills = codex_plugin_skills(plugin)
        for removed in REMOVED_SKILLS:
            assert removed not in skills
        # Retired reviewer agents must not have reappeared as skills.
        assert not (RETIRED_REVIEWER_AGENTS & skills)


def test_codex_marketplace_points_at_existing_plugins() -> None:
    marketplace = json.loads(
        (ROOT / ".agents" / "plugins" / "marketplace.json").read_text(encoding="utf-8")
    )
    for entry in marketplace["plugins"]:
        plugin_dir = ROOT / entry["source"]["path"]
        manifest = json.loads(
            (plugin_dir / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8")
        )
        assert manifest["name"] == entry["name"]


# --------------------------------------------------------------------------
# OpenCode: plugin-native distribution
# --------------------------------------------------------------------------


def test_opencode_reads_the_source_skill_directories() -> None:
    """OpenCode registers claude-plugins/*/skills directly; no copied payload exists."""
    index = (DIST / "opencode" / "plugin" / "index.js").read_text(encoding="utf-8")
    assert '"claude-plugins", plugin, "skills"' in index
    assert '["manifest-dev", "manifest-dev-tools"]' in index
    assert not (DIST / "opencode" / "skills").exists()
    assert not (DIST / "pi" / "skills").exists()


def test_opencode_ships_no_agents() -> None:
    # manifest-dev ships zero agents on every target; OpenCode drops its agents/ dir.
    assert not (DIST / "opencode" / "agents").exists()


def test_former_functional_agents_are_skills_in_every_dist() -> None:
    """The four converted agents now ship as skills, not agents."""
    assert {
        "check-pr",
        "poll-slack",
    } <= codex_plugin_skills("manifest-dev")
    assert "review-prompt" in codex_plugin_skills("manifest-dev-tools")
    for name in ("check-pr", "poll-slack"):
        assert name in CORE_SKILLS
    assert "review-prompt" in TOOLS_SKILLS


# --------------------------------------------------------------------------
# sync-tools references
# --------------------------------------------------------------------------


def test_sync_tools_is_a_wrapper_around_the_copy_script() -> None:
    """The per-host rewrite is retired: sync-tools runs scripts/sync_dist.py and
    lists the hand-maintained packaging files; its reference files are gone."""
    skill = (SYNC_TOOLS / "SKILL.md").read_text(encoding="utf-8")
    assert "python3 scripts/sync_dist.py" in skill
    assert "--check" in skill
    assert "claude-plugins/*/skills" in skill
    assert not (SYNC_TOOLS / "references").exists()
    assert len(skill.splitlines()) <= 40
    assert not list(DIST.rglob(".sync-meta.json"))


def test_codex_copy_matches_source() -> None:
    """dist/codex/plugins/*/skills is a byte-identical copy of claude-plugins/*/skills."""
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "sync_dist.py"), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr


def test_codex_distribution_is_plugin_native() -> None:
    readme = (DIST / "codex" / "README.md").read_text(encoding="utf-8")
    assert "codex plugin marketplace add doodledood/manifest-dev" in readme
    for plugin in ("manifest-dev", "manifest-dev-tools"):
        assert (
            DIST / "codex" / "plugins" / plugin / ".codex-plugin" / "plugin.json"
        ).is_file()
    assert not (DIST / "codex" / "agents").exists()


def test_goal_setting_backstop_is_universal_across_source_and_dist() -> None:
    """Unattended-run backstops are a portable capability, not a literal /goal rule.

    Source skills should tell the model to set a harness-native durable goal when the
    host exposes one, and to print a copy-pasteable completion contract only as the
    fallback. Pi must preserve that backstop instead of dropping it for lack of a
    `/goal` command; OpenCode/Codex must not regress to target-only `/goal` prose.
    """
    source_skill_files = [
        ROOT / "claude-plugins/manifest-dev/skills/figure-out/references/autonomous.md",
        ROOT / "claude-plugins/manifest-dev/skills/define/SKILL.md",
        ROOT / "claude-plugins/manifest-dev/skills/just-do/SKILL.md",
        ROOT / "claude-plugins/manifest-dev/skills/do/SKILL.md",
    ]
    for path in source_skill_files:
        text = path.read_text(encoding="utf-8")
        assert "goal-setting" in text, path
        assert "completion contract" in text, path
        assert "/goal" not in text, path

    source_docs = [
        ROOT / "README.md",
        ROOT / "claude-plugins/README.md",
        ROOT / "claude-plugins/manifest-dev/README.md",
        ROOT / "claude-plugins/manifest-dev/.claude-plugin/plugin.json",
    ]
    for path in source_docs:
        assert "goal-setting" in path.read_text(encoding="utf-8"), path

    dist_skill_files = [
        DIST / "codex/plugins/manifest-dev/skills/figure-out/references/autonomous.md",
        DIST / "codex/plugins/manifest-dev/skills/define/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/just-do/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/do/SKILL.md",
    ]
    stale_phrases = (
        "print the copy-pasteable full-chain backstop below so the user can relaunch under it",
        "launch `/do` under a `/goal`",
        "launch under a self-contained `/goal`",
        "print a copy-pasteable backstop for the run: a `/goal`",
    )
    for path in dist_skill_files:
        text = path.read_text(encoding="utf-8")
        assert "goal-setting" in text, path
        for stale in stale_phrases:
            assert stale not in text, f"{path}: stale goal wording {stale!r}"


def test_do_completion_contract_requires_auditable_gate_ledger() -> None:
    """The backstop must preserve mode, provenance, and incomplete-gate state."""
    do_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/do/SKILL.md",
    ]
    required_do_phrases = (
        "gate ledger covering every Acceptance Criterion and Global Invariant",
        # The ledger column that pins each verdict to the text it was reached
        # against; it names the gate itself now that `verify.instructions` is gone.
        "gate-text source",
        "selected verification mode",
        "evaluator provenance",
        "Whenever `/do` invokes `/escalate`, pass the manifest path",
        "That summary reports the selected verification mode",
        "Completion requires every listed gate to have fresh PASS evidence",
        "Use the selected reference's evidence/provenance wording",
    )
    for path in do_files:
        text = path.read_text(encoding="utf-8")
        for phrase in required_do_phrases:
            assert phrase in text, f"{path}: missing {phrase!r}"
        assert "verify.instructions" not in text, path
        assert not RETIRED_GATE_FIELDS.search(text), path

    done_files = [
        ROOT / "claude-plugins/manifest-dev/skills/done/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/done/SKILL.md",
    ]
    required_done_phrases = (
        "selected verification mode",
        "selected verification reference's evidence/provenance wording",
        "exactly from the supplied ledger and selected-reference wording",
        # Model provenance is relayed from `/do`, never chosen or restated here.
        "explicit or inherited verifier-model provenance",
        "fresh PASS evidence under the selected mode",
    )
    for path in done_files:
        text = path.read_text(encoding="utf-8")
        for phrase in required_done_phrases:
            assert phrase in text, f"{path}: missing {phrase!r}"
        # `/done` relays the selected reference's wording; it must not inline a
        # second copy of any mode's evidence policy.
        assert "independently verified per gate" not in text, path
        assert "independently verified by a consolidated verifier" not in text, path
        assert "`self` is executor self-verification" not in text, path
        assert "verify.instructions" not in text, path
        assert not RETIRED_GATE_FIELDS.search(text), path

    escalate_files = [
        ROOT / "claude-plugins/manifest-dev/skills/escalate/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/escalate/SKILL.md",
    ]
    required_escalate_phrases = (
        "selected verification mode",
        "explicit or inherited verifier-model provenance",
        "affected gate ledger entries including evaluator provenance",
        "Surface that policy/provenance with the blocker evidence",
    )
    for path in escalate_files:
        text = path.read_text(encoding="utf-8")
        for phrase in required_escalate_phrases:
            assert phrase in text, f"{path}: missing {phrase!r}"

    parent_goal_files = [
        ROOT / "claude-plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
        DIST / "codex/plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
    ]
    for path in parent_goal_files:
        text = path.read_text(encoding="utf-8")
        assert "manifest gate ledger" in text, path
        assert "fresh PASS evidence under the selected verification mode" in text, path
        assert "gate-text source" in text, path
        assert "evaluator provenance" in text, path
        assert "self-attestation" in text, path
        assert not RETIRED_GATE_FIELDS.search(text), path


def test_manifest_schema_is_topology_neutral_and_do_owns_execution_policy() -> None:
    """Schema, mode mechanics, and model choice must not collapse back together."""
    do_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/do/SKILL.md",
    ]
    for path in do_files:
        assert path.stat().st_mode & 0o111 == 0, path
        text = path.read_text(encoding="utf-8")
        assert "--verification per-gate|consolidated|self" in text, path
        assert "--verifier-model <model>" in text, path
        assert "defaults to `per-gate`" in text, path
        # The whole schema a gate carries: no evaluator-facing copy, no ordering
        # field, and a `kind` that is declared rather than inferred.
        assert (
            "A gate is a **title**, a **body**, an optional **why**, and a required "
            "**kind** (`judgment` or `deterministic`)" in text
        ), path
        assert "There is no default kind and none is inferred" in text, path
        # Both retired constructs stay rejected rather than migrated.
        assert (
            "Two shapes are the superseded schema and reject the same way" in text
        ), path
        assert "a gate carrying a `verify` block of any shape" in text, path
        assert (
            "a gate stating a `phase`, a field this workflow no longer has" in text
        ), path
        assert "Do not translate, ignore, migrate, or amend an old schema" in text, path
        assert not RETIRED_GATE_FIELDS.search(text), path
        assert "verify.instructions" not in text, path
        assert "None of them is written into the Manifest" in text, path
        assert "never change in response to cost" in text, path
        assert "load exactly one matching reference" in text, path
        assert "`references/per-gate-verification.md`" in text, path
        assert "`references/consolidated-verification.md`" in text, path
        assert "`references/self-verification.md`" in text, path
        assert "selected reference owns evaluator topology" in text, path
        assert "Evaluate gates through the selected reference's execution envelope" in (
            text
        ), path
        # Mode mechanics live in the loaded reference, never in the spine.
        assert "independent general-purpose verifier execution" not in text, path
        assert "Launch no verifier executions" not in text, path
        assert "Record provenance as `executor self-verification`" not in text, path
        assert "independently verified by a consolidated verifier" not in text, path
        assert "independently verified per gate" not in text, path

        refs = path.parent / "references"
        per_gate = refs / "per-gate-verification.md"
        consolidated = refs / "consolidated-verification.md"
        self_verification = refs / "self-verification.md"
        assert per_gate.is_file(), per_gate
        assert consolidated.is_file(), consolidated
        assert self_verification.is_file(), self_verification

        per_gate_text = per_gate.read_text(encoding="utf-8")
        assert (
            "Launch one fresh independent general-purpose verifier execution for "
            "every gate the spine marks eligible" in per_gate_text
        )
        assert "run those executions in parallel" in per_gate_text
        assert "Each execution returns one record for its own gate" in per_gate_text
        assert "Record provenance as `independent per-gate verifier`" in per_gate_text
        assert "independently verified per gate" in per_gate_text
        assert (
            "include the explicit verifier model or inherited model choice"
            in per_gate_text
        )

        consolidated_text = consolidated.read_text(encoding="utf-8")
        assert (
            "Launch one fresh independent general-purpose verifier execution for "
            "all gates the spine marks eligible" in consolidated_text
        )
        assert (
            "Have it evaluate every eligible gate separately and return a distinct "
            "record per gate" in consolidated_text
        )
        assert "Reject an overall verdict that lacks one" in consolidated_text
        assert (
            "a single gate's evidence or threshold never stands in for another's"
            in consolidated_text
        )
        assert "later phases remain unverified" not in consolidated_text
        assert (
            "include the explicit verifier model or inherited model choice"
            in consolidated_text
        )
        assert "independently verified by a consolidated verifier" in consolidated_text

        self_text = self_verification.read_text(encoding="utf-8")
        assert "Launch no verifier executions" in self_text
        assert (
            "read each gate the spine marks eligible from the Manifest by its ID"
            in (self_text)
        )
        assert "stop before a later phase" not in self_text
        assert "does not make this evidence independent" in self_text
        assert "Reject `--verifier-model`" in self_text
        assert "Record provenance as `executor self-verification`" in self_text
        assert "without claiming independence" in self_text

        for reference in (per_gate, consolidated, self_verification):
            assert reference.stat().st_mode & 0o111 == 0, reference
            reference_text = reference.read_text(encoding="utf-8")
            assert "Load this reference only" not in reference_text, reference
            assert not RETIRED_GATE_FIELDS.search(reference_text), reference

    define_files = [
        ROOT / "claude-plugins/manifest-dev/skills/define/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/define/SKILL.md",
    ]
    for path in define_files:
        text = path.read_text(encoding="utf-8")
        # `/define` validates an amend target against the same schema `/do` reads.
        assert (
            "a title, a body, an optional why, and a stated kind "
            "(`judgment` or `deterministic`)" in text
        ), path
        assert "`kind` is the only structured metadata" in text, path
        assert "A gate carrying a `verify` block of any shape" in text, path
        assert (
            "So is a gate stating a `phase`, a field this workflow no longer has"
            in text
        ), path
        assert (
            "a gate with no stated kind or one whose kind is unrecognised" in text
        ), path
        assert "verify.instructions" not in text, path
        assert "`verify.prompt`" not in text, path
        assert "`verify.model`" not in text, path
        assert not RETIRED_GATE_FIELDS.search(text), path
        assert "fresh `/define` regeneration" in text, path
        assert (
            "never amend, translate, or partially preserve an incompatible schema"
            in text
        ), path


def test_do_gate_eligibility_retries_every_non_passing_state() -> None:
    """FAIL and retryable BLOCKED gates must not deadlock the run.

    Eligibility is a property of each gate's own verdict state now that `phase`
    is retired, so every non-passing state has to name its way back to eligible
    and only a fresh PASS may settle.
    """
    do_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/do/SKILL.md",
    ]
    required_transitions = (
        "Every gate that is unverified, stale, FAIL, or retryable BLOCKED is eligible",
        "a fresh PASS is settled and does not re-run",
        "A FAIL remains eligible after repair",
        "a retryable BLOCKED remains eligible at its next check",
        "Unverified, stale, FAIL, and retryable BLOCKED gates re-evaluate when eligible",
        "a settled fresh PASS does not re-run",
        "Unverified, FAIL, stale, BLOCKED/actionable, or escalation-pending gates do "
        "not satisfy successful completion",
        "A terminal wait is reported as pending, never as success",
    )
    # Eligibility must not go back to being ordered by a retired manifest field.
    retired_phase_ordering = (
        "lowest phase",
        "later phases",
        "next phase",
    )
    for path in do_files:
        text = path.read_text(encoding="utf-8")
        for transition in required_transitions:
            assert transition in text, f"{path}: missing {transition!r}"
        for stale in retired_phase_ordering:
            assert stale not in text, f"{path}: stale phase ordering {stale!r}"


def test_every_operative_manifest_example_uses_the_current_gate_schema() -> None:
    """Every shipped gate example is written in the current gate schema.

    A gate example is an `AC-`/`INV-G` heading; its block must declare exactly one
    kind and carry neither retired field. One malformed example is enough to teach
    the schema wrong, so this walks every block rather than sampling.
    """
    authoring_roots = [
        ROOT / "claude-plugins/manifest-dev/skills/define",
        DIST / "codex/plugins/manifest-dev/skills/define",
    ]
    candidates = [ROOT / "claude-plugins/manifest-dev/README.md"]
    for authoring_root in authoring_roots:
        candidates.extend(authoring_root.rglob("*.md"))

    example_files: set[Path] = set()
    for path in candidates:
        text = path.read_text(encoding="utf-8")
        assert not RETIRED_GATE_FIELDS.search(text), path
        lines = text.splitlines()
        headings = [
            index
            for index, line in enumerate(lines)
            if GATE_EXAMPLE_HEADING.match(line)
        ]
        if not headings:
            continue
        example_files.add(path)
        for position, index in enumerate(headings):
            end = headings[position + 1] if position + 1 < len(headings) else len(lines)
            kinds = [
                line
                for line in lines[index + 1 : end]
                if GATE_KIND_LINE.match(line.strip())
            ]
            assert len(kinds) == 1, (
                f"{path}:{index + 1}: expected exactly one kind declaration, "
                f"found {kinds}"
            )

    required_examples = {
        "README.md",
        "SKILL.md",
        "MULTI_REPO.md",
        "PR_LIFECYCLE.md",
    }
    assert required_examples <= {path.name for path in example_files}


def test_operative_source_skills_have_no_legacy_schema_identifiers() -> None:
    operative_files = [
        ROOT / "README.md",
        ROOT / "CLAUDE.md",
        ROOT / "CONTEXT.md",
        ROOT / "claude-plugins/manifest-dev/README.md",
        ROOT / "claude-plugins/manifest-dev-tools/README.md",
        *(ROOT / "claude-plugins/manifest-dev/skills").rglob("*.md"),
        *(ROOT / "claude-plugins/manifest-dev-tools/skills").rglob("*.md"),
    ]
    for path in operative_files:
        text = path.read_text(encoding="utf-8")
        assert "verify.prompt" not in text, path
        assert "verify.model" not in text, path


def test_self_verification_never_claims_independence() -> None:
    roots = [
        ROOT / "claude-plugins/manifest-dev",
        ROOT / "claude-plugins/manifest-dev-tools",
        DIST / "codex/plugins",
    ]
    for root in roots:
        for path in root.rglob("*.md"):
            text = path.read_text(encoding="utf-8")
            assert not claims_self_verification_is_independent(text), path


def test_self_independence_detector_catches_semantic_variants() -> None:
    contradictory_claims = (
        "Self-verification uses an independent evaluator.",
        "Self-verification is independently verified.",
        "Independent self-verification is sufficient.",
        "The self mode relies on an independent verifier.",
        "Self verification is performed by an independent reviewer.",
    )
    for claim in contradictory_claims:
        assert claims_self_verification_is_independent(claim), claim

    valid_claims = (
        "Self-verification is not independent verification.",
        "Self-verification uses no independent evaluator.",
        "The host does not make this evidence independent. "
        "Record provenance as executor self-verification.",
    )
    for claim in valid_claims:
        assert not claims_self_verification_is_independent(claim), claim


def test_verification_policy_prompts_preserve_portable_boundaries() -> None:
    log_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/references/LOG.md",
        DIST / "codex/plugins/manifest-dev/skills/do/references/LOG.md",
    ]
    for path in log_files:
        text = path.read_text(encoding="utf-8")
        assert "default timestamped logs" in text, path
        assert "caller-supplied journal" in text, path
        assert "append a `Run initialized` boundary" in text, path
        assert "prior gate verdicts remain historical" in text, path
        assert "not carried into the new run" in text, path

    babysit_files = [
        ROOT / "claude-plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
        DIST / "codex/plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
    ]
    for path in babysit_files:
        text = path.read_text(encoding="utf-8")
        assert "appends a new run boundary and starts a fresh gate ledger" in text, path
        assert "prior verdicts remain historical" in text, path
        assert "not carried into the active run" in text, path

    consolidated_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/references/"
        "consolidated-verification.md",
        DIST / "codex/plugins/manifest-dev/skills/do/references/"
        "consolidated-verification.md",
    ]
    for path in consolidated_files:
        text = path.read_text(encoding="utf-8")
        assert "same current artifact or project state" in text, path
        assert "relevant head SHA or SHAs" in text, path
        assert "without inventing a head" in text, path
        assert "from the current head" not in text, path

    define_files = [
        ROOT / "claude-plugins/manifest-dev/skills/define/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/define/SKILL.md",
    ]
    for path in define_files:
        text = path.read_text(encoding="utf-8")
        assert "gate-evaluation lookup data" in text, path
        assert "verifier-agent lookup data" not in text, path

    auto_files = [
        ROOT / "claude-plugins/manifest-dev/skills/auto/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/auto/SKILL.md",
    ]
    for path in auto_files:
        text = path.read_text(encoding="utf-8")
        assert "Parse only top-level option uses" in text, path
        assert "quoted or topic mentions remain task text" in text, path


def test_define_task_gates_do_not_select_evaluator_topology() -> None:
    task_roots = [
        ROOT / "claude-plugins/manifest-dev/skills/define/tasks",
        DIST / "codex/plugins/manifest-dev/skills/define/tasks",
    ]
    gate_files = (
        "WRITING.md",
        "TECH_DESIGN.md",
        "BLOG.md",
        "DOCUMENT.md",
        "FEATURE.md",
        "research/RESEARCH.md",
    )
    for task_root in task_roots:
        for relative in gate_files:
            path = task_root / relative
            text = path.read_text(encoding="utf-8")
            assert "| Agent |" not in text, path
            assert "| general-purpose |" not in text, path
            assert "writing-reviewer" not in text, path

    project_context = (ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    assert "tables with Agent + Threshold" not in project_context


def test_operational_guidance_has_no_stale_per_gate_topology() -> None:
    files = [
        ROOT / "README.md",
        ROOT / "claude-plugins/manifest-dev-tools/README.md",
        ROOT
        / "claude-plugins/manifest-dev/skills/define/references/WRITING-REFERENCE.md",
        ROOT / "claude-plugins/manifest-dev/skills/define/references/BABYSIT_MODE.md",
        ROOT / "claude-plugins/manifest-dev/skills/review-code/SKILL.md",
        DIST
        / "codex/plugins/manifest-dev/skills/define/references/WRITING-REFERENCE.md",
        DIST / "codex/plugins/manifest-dev/skills/define/references/BABYSIT_MODE.md",
        DIST / "codex/plugins/manifest-dev/skills/review-code/SKILL.md",
    ]
    stale_phrases = (
        "general-purpose subagent or verifier execution per gate",
        "Pass this file as context to a general-purpose verifier",
        "the verifier (the general-purpose agent activating",
        "Pi Harness-level Do outcome gate",
        "typically spawn a general-purpose agent",
    )
    for path in files:
        text = path.read_text(encoding="utf-8")
        for phrase in stale_phrases:
            assert phrase not in text, f"{path}: stale topology wording {phrase!r}"
        assert not RETIRED_GATE_FIELDS.search(text), path

    readme = (ROOT / "claude-plugins/manifest-dev/README.md").read_text(
        encoding="utf-8"
    )
    example = readme.split("### Deliverable 1: Login round-trip", 1)[1].split(
        "````", 1
    )[0]
    # The deliverable's two gates each declare a kind and nothing else — one of
    # each, so the example still shows both re-verification behaviors.
    assert example.count("Deterministic gate.") == 1
    assert example.count("Judgment gate.") == 1
    assert not RETIRED_GATE_FIELDS.search(example)


def test_parent_workflows_forward_policy_without_putting_it_in_manifests() -> None:
    auto_files = [
        ROOT / "claude-plugins/manifest-dev/skills/auto/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/auto/SKILL.md",
    ]
    babysit_files = [
        ROOT / "claude-plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
        DIST / "codex/plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
    ]
    for path in auto_files:
        text = path.read_text(encoding="utf-8")
        assert "--verification per-gate|consolidated|self" in text, path
        assert "--verifier-model <model>" in text, path
        assert "Never write either" in text, path
        assert "into the Manifest" in text, path
        assert "load the matching sibling `/do` reference" in text, path
        assert "the reference, not `/auto`, owns mode-specific" in text, path
        assert (
            "Remove parsed flags from the task before `/define`, and forward them only to `/do`."
            in text
        ), path
        assert "independently verified per gate" not in text, path
        assert "independently verified by a consolidated verifier" not in text, path
        assert "means executor self-verification" not in text, path

    for path in babysit_files:
        text = path.read_text(encoding="utf-8")
        assert "--verification per-gate|consolidated|self" in text, path
        assert "--verifier-model <model>" in text, path
        assert "Never write either" in text, path
        assert "into the Manifest" in text, path
        assert re.search(
            r"load the matching `(?:manifest-dev:)?do` verification reference",
            text,
        ), path
        assert "the reference, not Babysit PR, owns mode-specific" in text, path
        assert (
            "selected verification reference's required evidence/provenance wording"
            in (text)
        ), path
        assert "independently verified per gate" not in text, path
        assert "independently verified by a consolidated verifier" not in text, path
        assert "as executor self-verification" not in text, path
        assert re.search(
            r"After resolving the manifest path, invoke `(?:manifest-dev:)?do` "
            r"on it with the parsed verification options",
            text,
        ), path


def test_review_pr_manifest_mode_remains_independently_per_gate() -> None:
    references = [
        ROOT
        / "claude-plugins/manifest-dev-tools/skills/review-pr/references/MANIFEST_MODE.md",
        DIST
        / "codex/plugins/manifest-dev-tools/skills/review-pr/references/MANIFEST_MODE.md",
    ]
    for path in references:
        text = path.read_text(encoding="utf-8")
        assert (
            "one fresh independent verifier execution per Acceptance Criterion" in text
        )
        # The reviewer reads the canonical gate text from the manifest rather than
        # a copy handed to it — the guarantee the retired `verify.instructions`
        # verbatim-pass rule used to carry.
        assert "each pointed at that gate by ID" in text
        assert (
            "told to read the gate's text from the file rather than receiving a "
            "copy of it" in text
        )
        assert "regardless of which `/do --verification` mode" in text
        assert "model choice is not manifest data" in text
        # Manifest mode validates against the same current schema `/do` enforces.
        assert (
            "A gate is a title, a body, an optional why, and a required kind "
            "(`judgment` or `deterministic`)" in text
        )
        assert "a gate carrying a `verify` block of any shape" in text
        assert (
            "a gate stating a `phase` — a field the manifest schema no longer has"
            in (text)
        )
        assert "verify.instructions" not in text
        assert not RETIRED_GATE_FIELDS.search(text)


def test_auto_investigation_keeps_read_bar_without_a_phase_goal() -> None:
    """Suppress the child goal before its generic standalone/parent rules run."""
    for root in (
        ROOT / "claude-plugins/manifest-dev/skills",
        DIST / "codex/plugins/manifest-dev/skills",
    ):
        auto = (root / "auto/SKILL.md").read_text(encoding="utf-8")
        child = (root / "figure-out/references/autonomous.md").read_text(
            encoding="utf-8"
        )
        assert "keep its full Read bar as the checkpoint before define" in auto
        assert "When chained under auto" in child
        assert "do not set or print a continuation goal" in child
        assert child.index("When chained under auto") < child.index(
            "Otherwise, your first action"
        )
        assert "Outside auto, this is the standalone-run backstop" in child


def test_autonomous_figure_out_supplements_weak_parent_backstops() -> None:
    """A weak parent is supplemented without replacing it with a Read-only goal."""
    files = [
        ROOT / "claude-plugins/manifest-dev/skills/figure-out/references/autonomous.md",
        DIST / "codex/plugins/manifest-dev/skills/figure-out/references/autonomous.md",
    ]
    required_phrases = (
        "Suppress it only when",
        "carries this Read-completion contract",
        "If the visible parent is weak",
        'only says "Read named"',
        "do not replace or narrow that parent into a Read-only goal",
        "Augment the parent only when the harness can do so without narrowing it",
        "print or carry this Read-level contract as a local checkpoint",
        "preserve the broader parent",
    )
    forbidden_phrases = (
        "supplement it by setting or printing this Read-level contract",
    )
    for path in files:
        text = path.read_text(encoding="utf-8")
        for phrase in required_phrases:
            assert phrase in text, f"{path}: missing {phrase!r}"
        for phrase in forbidden_phrases:
            assert phrase not in text, f"{path}: forbidden {phrase!r}"


def test_autonomous_diagnosis_goal_requires_mechanism_or_earned_underdetermination() -> (
    None
):
    expected = (
        "For diagnosis-shaped work, finding where the symptom concentrates is only "
        "localization, not a complete Read: name the concrete mechanism — the "
        "variable, difference, or sequence that produces the symptom, including "
        "why this case differs when the question is comparative — or earn an "
        "underdetermined Read by naming the surviving explanations and showing "
        "which feasible probes that could distinguish them were run, what they "
        "showed, or why they were blocked."
    )
    files = [
        ROOT / "claude-plugins/manifest-dev/skills/figure-out/references/autonomous.md",
        DIST / "codex/plugins/manifest-dev/skills/figure-out/references/autonomous.md",
    ]
    for path in files:
        text = path.read_text(encoding="utf-8")
        assert expected in text, path


def test_continuation_ownership_preserves_babysit_parent() -> None:
    """Nested workflow skills should not set competing narrower goals."""
    define_files = [
        ROOT / "claude-plugins/manifest-dev/skills/define/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/define/SKILL.md",
    ]
    for path in define_files:
        text = path.read_text(encoding="utf-8")
        assert "Deliver <deliverables>" not in text, path
        assert "/define does not set a separate /do goal" in text, path
        assert (
            "/do reads the manifest and owns the manifest-completion contract" in text
        ), path

    do_files = [
        ROOT / "claude-plugins/manifest-dev/skills/do/SKILL.md",
        DIST / "codex/plugins/manifest-dev/skills/do/SKILL.md",
    ]
    for path in do_files:
        text = path.read_text(encoding="utf-8")
        assert "Before implementation, including when called by /auto" in text, path
        assert "broader parent workflow backstop" in text, path
        assert "do not set or print a second narrower goal" in text, path

    babysit_files = [
        ROOT / "claude-plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
        DIST / "codex/plugins/manifest-dev-tools/skills/babysit-pr/SKILL.md",
    ]
    for path in babysit_files:
        text = path.read_text(encoding="utf-8")
        assert (
            "including the `--manifest` path where `/define` is skipped" in text
        ), path
        assert "outer backstop for the tend" in text, path
        assert "should not set or print competing narrower goals" in text, path


# --------------------------------------------------------------------------
# Pi: skill-only package + prompt aliases
# --------------------------------------------------------------------------


def test_pi_package_metadata_points_to_source_skills_and_prompts() -> None:
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))

    assert package["name"] == "@doodledood/manifest-dev-pi"
    assert re.fullmatch(r"\d+\.\d+\.\d+", package["version"])
    assert "pi-package" in package["keywords"]
    assert package["pi"] == {
        "skills": [
            "./claude-plugins/manifest-dev/skills",
            "./claude-plugins/manifest-dev-tools/skills",
        ],
        "prompts": ["./dist/pi/prompts"],
    }
    for rel in package["pi"]["skills"]:
        assert (ROOT / rel).is_dir(), rel
    assert "extensions" not in package["pi"]
    assert "workspaces" not in package
    assert "exports" not in package
    assert not (ROOT / "pi" / "extensions").exists()
    assert not (ROOT / "packages" / "manifest-dev-pi-tools").exists()


def test_pi_dist_carries_only_prompt_aliases() -> None:
    prompt_files = {path.stem for path in (DIST / "pi" / "prompts").glob("*.md")}
    assert prompt_files == set(PI_PROMPTS)
    assert not (DIST / "pi" / "skills").exists()
    assert not (DIST / "pi" / "component-namespaces.json").exists()


def test_pi_prompt_aliases_expand_to_matching_skills() -> None:
    expected = {
        "do.md": "Use the do skill with: $ARGUMENTS",
        "auto.md": "Use the auto skill with: $ARGUMENTS",
        "babysit-pr.md": "Use the babysit-pr skill with: $ARGUMENTS",
    }
    for filename, body in expected.items():
        text = (DIST / "pi" / "prompts" / filename).read_text(encoding="utf-8")
        assert body in text
        assert "description:" in text


def test_pi_live_docs_do_not_claim_runtime_verifier_fanout() -> None:
    live_paths = [
        ROOT / "README.md",
        DIST / "pi" / "README.md",
    ]
    stale = (
        "manifest-verifier-max-concurrent",
        "MANIFEST_DEV_VERIFIER_MAX_CONCURRENT",
        "manifest_dev_request_verification",
        "manifest_dev_report_outcome",
        "WAIT-PENDING",
        "JSON subprocess verifier fanout",
        "runtime-owned verification",
        "done outcome",
    )
    for path in live_paths:
        text = path.read_text(encoding="utf-8")
        for phrase in stale:
            assert phrase not in text, f"{path}: stale Pi runtime claim {phrase!r}"


def _without_cross_host_review_pr_markers(text: str) -> str:
    """Remove review-pr's literal hidden GitHub marker before skill-id scans.

    The marker is cross-host comment metadata (`<!-- manifest-dev:review-pr ... -->`),
    not a skill activation id; the review-pr skill explicitly says not to namespace-
    rewrite it or comments posted by one host stop matching another's.
    """
    return re.sub(r"<!-- manifest-dev:review-pr[^>]*-->", "", text)


# --- Durable source<->dist drift guards -----------------------------------------
# These sweep EVERY skill markdown on each surface so a future /sync-tools that
# regenerates dist (it force-full-regenerates when the reference files change)
# cannot silently reintroduce the drift classes this PR fixed. They assert the
# per-target invariant holds everywhere, not just on the files edited by hand.

SOURCE_SKILL_ROOTS = (
    ROOT / "claude-plugins" / "manifest-dev" / "skills",
    ROOT / "claude-plugins" / "manifest-dev-tools" / "skills",
)
CODEX_COPY_ROOTS = (
    DIST / "codex" / "plugins" / "manifest-dev" / "skills",
    DIST / "codex" / "plugins" / "manifest-dev-tools" / "skills",
)
# Malformed activation forms that read as a plugin name followed by a skill name —
# they resolve nowhere and must never appear on any surface.
_MALFORMED_FORMS = ("manifest-dev check-pr skill",)  # space form


def _skill_markdowns(*roots: Path) -> list[Path]:
    return [p for root in roots for p in root.rglob("*.md")]


def test_skill_activation_names_are_bare_on_every_surface() -> None:
    """Cross-skill references name the skill bare (`check-pr`, `review-prompt`), never
    plugin-qualified: every host reads the same text, and a plugin namespace is one
    host's primitive. review-pr's hidden GitHub markers are literals, not references,
    and keep their qualifier inside the HTML comment."""
    qualified = re.compile(r"manifest-dev(?:-tools)?:[a-z]")

    for rel in (
        "claude-plugins/manifest-dev/skills/define/SKILL.md",
        "claude-plugins/manifest-dev/skills/define/tasks/PR_LIFECYCLE.md",
    ):
        text = (ROOT / rel).read_text(encoding="utf-8")
        assert "manifest-dev check-pr skill" not in text
        assert "`check-pr`" in text
    prompting = (
        ROOT / "claude-plugins/manifest-dev/skills/define/tasks/PROMPTING.md"
    ).read_text(encoding="utf-8")
    assert "activates the `review-prompt` skill" in prompting

    for path in _skill_markdowns(*SOURCE_SKILL_ROOTS, *CODEX_COPY_ROOTS):
        text = _without_cross_host_review_pr_markers(path.read_text(encoding="utf-8"))
        assert not qualified.search(text), path

    review_pr = (
        ROOT / "claude-plugins/manifest-dev-tools/skills/review-pr/SKILL.md"
    ).read_text(encoding="utf-8")
    assert "<!-- manifest-dev:review-pr -->" in review_pr
    assert "<!-- manifest-dev:review-pr judgment -->" in review_pr


def test_no_malformed_activation_forms_on_any_surface() -> None:
    for path in _skill_markdowns(*SOURCE_SKILL_ROOTS, *CODEX_COPY_ROOTS):
        text = path.read_text(encoding="utf-8")
        for bad in _MALFORMED_FORMS:
            assert bad not in text, f"{path}: malformed activation form {bad!r}"


def test_check_pr_stays_workflow_neutral_on_every_surface() -> None:
    """check-pr is a workflow-neutral reporter and should not grow caller-specific
    pending tokens or workflow routing state in source or dist copies."""
    check_pr_copies = [
        ROOT / "claude-plugins/manifest-dev/skills/check-pr/SKILL.md",
        DIST
        / "codex"
        / "plugins"
        / "manifest-dev"
        / "skills"
        / "check-pr"
        / "SKILL.md",
    ]
    for path in check_pr_copies:
        assert path.exists(), path
        forbidden = "WAIT" + "-PENDING"
        assert forbidden not in path.read_text(encoding="utf-8"), path
